### PR TITLE
Add put/post for design docs

### LINKED ISSUE #41: Getting 405 PUT is not allowed when trying to insert a _design doc with nano
I seem to be getting a 405 PUT not allowed error when trying to insert a design document;

```js
{ [Error: PUT is not allowed]
  name: 'Error',
  statusCode: 405,
  body: { code: 'MethodNotAllowedError', message: 'PUT is not allowed' },
  scope: 'couch',
  request: 
   { method: 'PUT',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
[...]
```

I'm simply doing the following with nano after creating a database:

```js
var design = {
  "views": {
    "all": {
      map: function(doc) {
        if (doc._id) emit(doc._id, doc);
      }
    }
  }
};

db.insert(design, '_design/tweets', function(err, res) {
  if (err) return console.log(err);
  console.log('Inserted!');
});
```

This gives the correct response when using a real couchdb database, but seems to fail when using `mock-couch`.

### PR DESCRIPTION
**Pull request by dermidgen**
Closes #41

### CODE REVIEW

**Comment by dermidgen** [comment]
@chris-l - I didn't update unit tests yet; but I do plan on that.

**Comment by chris-l** [comment]
Yeah, I test it and it works perfectly!

I have added a single unit test (only one at the moment), and fixed some validation issues.
And if you want to contribute extra unit tests, you are more than welcome :)
Just pull the latest commits and check the unit test at `test/views.spec.js` for reference.

Thanks a lot!

**Comment by dermidgen** [comment]
Oh dude - you rock! Thank you for adding a test and merging so quickly.

**Comment by RuizhiWang** [comment]
Hi there,
Can somebody publish this fix to npm package? The 0.1.6 version was published 6 month ago and doesn't have this fix.
Really look forward to seeing the npm package include this fix, rather than install from git for this specific version.
Thanks very much.

**Pull request merged**
