### PR TITLE
_changes mock

### PR DESCRIPTION
**Pull request by conor-mac-aoidh**
A partial implementation of a mock couchdb changes stream.

Supports query params:

feed=continuous
heartbeat=X

The implementation is partial as it always returns 'since=now' and a sequence number cannot be specified.

Also, documents are always returned - ie. include_docs is used for every request.

Has been tested and working!

Conor

### CODE REVIEW

**Comment by chris-l** [comment]
Ah nice! Give me a few hours to check it. I think I'll have the time to check it in the night.

(by the way, it says travis had a failure)

**Comment by conor-mac-aoidh** [comment]
Updated to enable 'since' and 'include_docs' params usage.

Oh didn't realise travis was failing. When I said I tested, I meant within my own app/framework. But I will have a look at this tonight again and get the tests passing!

**Comment by conor-mac-aoidh** [comment]
Travis is passing now and I've added a test case for the changes stream implementation.

**Comment by chris-l** [comment]
Thank you! I have implemented the commits you sent me.

But I did a few changes to one of them (the commit were you accidentally added some files).
For that reason, I didn't imported with the merge button.

By the way, I also did some other changes I been planing for some time (mostly using ramda instead of underscore and using jslint instead of jshint)

Thanks a lot for your contribution!

**Pull request closed without merging**
